title: "Rudraksh Kapil"
author: "Rudraksh Kapil"
description: "Rudraksh's Portfolio"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true              # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title:"Home"}
  - {file: "research.md", title:"Research"}
  - {file: "projects.md", title:"Projects"}
  # - {file: "experience.md", title:"Experience"}
  - {file: "lab.md", title:"Forests"}
  # - {file: "thesis_page.md", title:"Thesis"}
  - {file: "resources/general/Rudraksh-Kapil-CV.pdf", title:"CV"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:rkapil@ualberta.ca"}
  - {title: Github, icon: github, url: "https://github.com/rudrakshkapil"}
  - {title: LinkedIn, icon: linkedin, url: "https://linkedin.com/in/rudrakshkapil"}
  - {title: CV, icon: user, url: "resources/general/Rudraksh-Kapil-CV.pdf"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
